---
- include_role:
    name: andrewrothstein.unarchivedeps
- include_role:
    name: andrewrothstein.temurin
  vars:
    openjdk_app: jre
- name: check for existing install at {{ nexus_repo_install_dir }}
  become: true
  become_user: root
  stat:
    path: '{{ nexus_repo_install_dir }}'
  changed_when: false
  register: nexus_repo_binary
- when: not nexus_repo_binary.stat.exists
  block:
    - name: downloading {{ nexus_repo_tgz_url }} to {{ nexus_repo_tmp_tgz }}
      become: true
      become_user: root
      get_url:
        url: '{{ nexus_repo_tgz_url }}'
        dest: '{{ nexus_repo_tmp_tgz }}'
        checksum: '{{ nexus_repo_checksum }}'
        mode: 0644
    - name: unarchiving {{ nexus_repo_tmp_tgz }} to {{ nexus_repo_parent_install_dir }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ nexus_repo_tmp_tgz }}'
        dest: '{{ nexus_repo_parent_install_dir }}'
        creates: '{{ nexus_repo_install_dir }}'
  always:
    - name: cleanup
      become: true
      become_user: root
      file:
        path: '{{ nexus_repo_tmp_tgz }}'
        state: absent

- name: linking {{ nexus_repo_install_dir }} to {{ nexus_repo_link_dir }}
  become: true
  become_user: root
  file:
    src: '{{ nexus_repo_install_dir }}'
    dest: '{{ nexus_repo_link_dir }}'
    state: link

- name: adding to default shell PATH...
  become: true
  become_user: root
  with_items:
    - f: nexus.sh
      d: /etc/profile.d
      m: '0644'
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m }}'
