---
- name: Installing andrewrothstein.temurin
  ansible.builtin.include_role:
    name: andrewrothstein.temurin
  vars:
    temurin_app: jre
- name: Check for existing install at {{ nexus_repo_install_dir }}
  become: true
  become_user: root
  ansible.builtin.stat:
    path: '{{ nexus_repo_install_dir }}'
  changed_when: false
  register: nexus_repo_binary
- name: Downloading and installing nexus-repo
  when: not nexus_repo_binary.stat.exists
  block:
    - name: Downloading {{ nexus_repo_tgz_url }} to {{ nexus_repo_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ nexus_repo_tgz_url }}'
        dest: '{{ nexus_repo_tmp_tgz }}'
        checksum: '{{ nexus_repo_checksum }}'
        mode: '644'
    - name: Installing andrewrothstein.unarchivedeps
      ansible.builtin.include_role:
        name: andrewrothstein.unarchivedeps
    - name: Unarchiving {{ nexus_repo_tmp_tgz }} to {{ nexus_repo_parent_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ nexus_repo_tmp_tgz }}'
        dest: '{{ nexus_repo_parent_install_dir }}'
        creates: '{{ nexus_repo_install_dir }}'
  always:
    - name: Cleanup
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ nexus_repo_tmp_tgz }}'
        state: absent

- name: Linking {{ nexus_repo_install_dir }} to {{ nexus_repo_link_dir }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ nexus_repo_install_dir }}'
    dest: '{{ nexus_repo_link_dir }}'
    state: link

- name: Ddding to default shell PATH...
  become: true
  become_user: root
  with_items:
    - f: nexus.sh
      d: /etc/profile.d
      m: '644'
  ansible.builtin.template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m }}'
